// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgtutqbqkfcqmqqjcglq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndHV0cWJxa2ZjcW1xcWpjZ2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzcyMzQsImV4cCI6MjA1OTcxMzIzNH0.62lZ8mH1Fm5N0zllNKmtGQGrgnsJ_rurfyjprhGsi3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);